devices:
- description: Система вентиляции и климат-контроля
  device_id: 1
  device_type: KUB-1063
  enabled: true
  location: Корпус №1
  name: Устройство 1
  slave_id: 1
- description: Система обогрева для тестирования
  device_id: 2
  device_type: KUB-1112
  enabled: true
  location: Тестовая зона
  name: Устройство 2
  slave_id: 2
