devices:
- description: Автоскан EDGE
  device_id: 1
  device_type: VFD-INVERTER
  enabled: true
  name: 'VFD-INVERTER #1'
  poll_interval: 20.0
  room: ПТ-1
  slave_id: 1
- description: Автоскан EDGE
  device_id: 2
  device_type: KUB-1063
  enabled: true
  name: 'KUB-1063 #2'
  poll_interval: 20.0
  room: ПТ-1
  slave_id: 2
- description: Автоскан EDGE
  device_id: 3
  device_type: KUB-1112
  enabled: true
  name: 'KUB-1112 #3'
  poll_interval: 20.0
  room: СВК-2
  slave_id: 3
- description: Автоскан EDGE
  device_id: 4
  device_type: ESQ-230
  enabled: true
  name: 'ESQ-230 #4'
  poll_interval: 20.0
  room: СВК-2
  slave_id: 4
